version: '2.1'

services:
# web:
#   #restart: always
#   build: ./application/web
#   expose:
#     - "8000"
#   volumes:
#     - static-content:/usr/src/app/web/share_ai/static
#     #- session-data:/home/flask/app/ #not needed as we will use client side sessions
#
#   #spins up a reverse proxy to assign workers to incoming requests for web resources
#   command: /usr/local/bin/gunicorn -w 2 -b :8000 share_ai:app



 db:
   build: ./database/
   healthcheck:
     test: ["CMD-SHELL", "pg_isready -U postgres"]
     interval: 5s
     timeout: 5s
     retries: 5
   environment:
     POSTGRES_PASSWORD: password
   expose:
     - 5423
   ports:
     - 5432:5432
   volumes:
     - postgres-data:/var/lib/postgresql/data


 api:
   #restart: always
   build: ./application/api
   depends_on:
     db:
         condition: service_healthy
   expose:
     - "8000"
   environment:
      - SINGULAR_SO=/home/sage/sage/local/lib/libsingular_resources-4.1.1.so
      - LDFLAGS=-L/home/sage/sage/local/lib -Wl,-rpath,/home/sage/sage/local/lib
      - LIBRARY_PATH=/home/sage/sage/local/lib:/usr/lib/x86_64-linux-gnu
      - SAGE_LOCAL=/home/sage/sage/local
      - SAGE_SPKG_INST=/home/sage/sage/local/var/lib/sage/installed
      - SINGULARPATH=/home/sage/sage/local/share/singular
   volumes:
     - static-content:/usr/src/app/api/graphbrain/static
     #- session-data:/home/flask/app/ #not needed as we will use client side sessions

   #spins up a reverse proxy to assign workers to incoming requests for web resources
   command: /home/sage/sage/local/bin/gunicorn -w 2 -b :8000 graphbrain_api:app

 computer:
   #restart: always
   build: ./application/computer
   depends_on:
     - api
   environment:
     - SINGULAR_SO=/home/sage/sage/local/lib/libsingular_resources-4.1.1.so
     - LDFLAGS=-L/home/sage/sage/local/lib -Wl,-rpath,/home/sage/sage/local/lib
     - LIBRARY_PATH=/home/sage/sage/local/lib:/usr/lib/x86_64-linux-gnu
     - SAGE_LOCAL=/home/sage/sage/local
     - SAGE_SPKG_INST=/home/sage/sage/local/var/lib/sage/installed
     - SINGULARPATH=/home/sage/sage/local/share/singular
     - PYTHONPATH="/home/sage/"
   command: python compute_values.py


 nginx:
   #restart: always
   image: graphbrain
   build: ./nginx
   #mem_limit: 256m #set memory limit for nginx so it reclaims memory
   ports:
     - 80:80

   volumes:
     - /www/static
#   volumes_from:
#     - web
   depends_on:
     db:
         condition: service_healthy
volumes:
  postgres-data: #a volume that stores postgres data
  #session-data: #a volume for storing session data
  static-content: #a volume for storing static content such as images