version: '2.1'

services:
  api:
    build: ./application/api
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
    volumes:
      - ./application/api/:/home/flask/app/api
    command: flask run --host=0.0.0.0 --port 8000